# Generated by Django 3.2.9 on 2021-12-01 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEST_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отделы',
                'verbose_name_plural': 'Отдел',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='test_2',
            options={'ordering': ['department', 'room'], 'verbose_name': 'Кабинеты', 'verbose_name_plural': 'Кабинет'},
        ),
        migrations.AddField(
            model_name='test_1',
            name='department',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.PROTECT, to='main.test_3', verbose_name='Отдел'),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='test_2',
            name='department',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.PROTECT, to='main.test_3', verbose_name='Отдел'),
            preserve_default=1,
        ),
    ]
