# Generated by Django 3.2.9 on 2021-12-01 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211201_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_1',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.test_3', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='test_2',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.test_3', verbose_name='Отдел'),
        ),
    ]
