# Generated by Django 3.2.9 on 2021-12-01 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211201_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('tech_id', models.IntegerField(verbose_name='Тех. ID')),
                ('invent_id', models.CharField(max_length=20, verbose_name='Инвентарный ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dep', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
                'ordering': ['name', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('bool', models.BooleanField(default=False)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inv', verbose_name='оборудование')),
            ],
            options={
                'verbose_name': 'Ремонт',
                'verbose_name_plural': 'Ремонты',
                'ordering': ['bool'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=40, verbose_name='Кабинет')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.dep', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['department', 'room'],
            },
        ),
        migrations.RemoveField(
            model_name='test_2',
            name='department',
        ),
        migrations.DeleteModel(
            name='TEST_1',
        ),
        migrations.DeleteModel(
            name='TEST_2',
        ),
        migrations.DeleteModel(
            name='TEST_3',
        ),
        migrations.AddField(
            model_name='inv',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.room', verbose_name='Кабинет'),
        ),
    ]
